name: Pages

on:
  push:
    tags:
      - "v*"

jobs:
  pages:
    name: Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Deploy docs
        env:
          GIT_COMMITTER_NAME: CI
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          # Get most recent git tag
          # https://stackoverflow.com/a/7261049
          VERSION=$(git describe --tags --abbrev=0)
          mike deploy $VERSION latest --update-aliases --push
